---
driver:
  name: vagrant
# driver:
#   name: docker

provisioner:
  name: chef_zero

verifier:
  name: inspec

# platforms:
#   - name: centos-5
#   - name: centos-6
#   - name: centos-7
#   - name: ubuntu-precise
#   - name: ubuntu-trusty
#   - name: ubuntu-xenial
#   - name: debian-7
#   - name: debian-8

platforms:
  - name: centos-5.11
  - name: centos-6.8
  - name: centos-7.2
  - name: debian-7.11
  - name: debian-8.5
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[ksplice::default]
    attributes:
